using './document-analysis-reconciliation-containerapp.module.bicep'

param aca_env_outputs_azure_container_apps_environment_default_domain = '{{ .Env.ACA_ENV_AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}'
param aca_env_outputs_azure_container_apps_environment_id = '{{ .Env.ACA_ENV_AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}'
param aca_env_outputs_azure_container_registry_endpoint = '{{ .Env.ACA_ENV_AZURE_CONTAINER_REGISTRY_ENDPOINT }}'
param aca_env_outputs_azure_container_registry_managed_identity_id = '{{ .Env.ACA_ENV_AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}'
param document_analysis_reconciliation_containerimage = '{{ .Image }}'
param document_analysis_reconciliation_identity_outputs_id = '{{ .Env.WEBAPI_IDENTITY_ID }}'
param document_analysis_reconciliation_identity_outputs_clientid = '{{ .Env.WEBAPI_IDENTITY_CLIENTID }}'
param dbserver_outputs_sqlserverfqdn = '{{ .Env.DBSERVER_SQLSERVERFQDN }}'
param storage_outputs_queueendpoint = '{{ .Env.STORAGE_QUEUEENDPOINT }}'
